# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

lakion_cms_admin:
    resource: "@LakionCmsPlugin/Resources/config/app/admin_routing.yml"
    prefix: /admin # root path of SyliusAdmin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

lakion_cms_shop:
    resource: "@LakionCmsPlugin/Resources/config/app/shop_routing.yml"
