sylius_grid:
    grids:
        sylius_admin_channel:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.channel.class%"
            sorting:
                nameAndDescription: asc
            fields:
                code:
                    type: twig
                    label: sylius.ui.code
                    path: .
                    sortable: code
                    options:
                        template: "@SyliusAdmin/Channel/Grid/Field/code.html.twig"
                nameAndDescription:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    sortable: name
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
                hostname:
                    type: twig
                    label: sylius.ui.hostname
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/Channel/Grid/Field/hostname.html.twig"
                themeName:
                    type: twig
                    label: sylius.ui.theme
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/Channel/Grid/Field/themeName.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
