sylius_grid:
    grids:
        sylius_admin_country:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.country.class%"
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    sortable: code
                    options:
                        template: "@SyliusAdmin/Country/Grid/Field/name.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
